[2023-11-02T17:58:20.590+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.tsk_glue_job_trigger manual__2023-11-02T17:57:39.434814+00:00 [queued]>
[2023-11-02T17:58:20.596+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.tsk_glue_job_trigger manual__2023-11-02T17:57:39.434814+00:00 [queued]>
[2023-11-02T17:58:20.596+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-11-02T17:58:20.659+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): tsk_glue_job_trigger> on 2023-11-02 17:57:39.434814+00:00
[2023-11-02T17:58:20.662+0000] {standard_task_runner.py:57} INFO - Started process 1690 to run task
[2023-11-02T17:58:20.665+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'tsk_glue_job_trigger', 'manual__2023-11-02T17:57:39.434814+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpkif6vqn6']
[2023-11-02T17:58:20.667+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask tsk_glue_job_trigger
[2023-11-02T17:58:20.702+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.tsk_glue_job_trigger manual__2023-11-02T17:57:39.434814+00:00 [running]> on host ip-172-31-12-44.eu-west-2.compute.internal
[2023-11-02T17:58:20.752+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='tsk_glue_job_trigger' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T17:57:39.434814+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T17:57:39.434814+00:00'
[2023-11-02T17:58:20.757+0000] {base.py:73} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2023-11-02T17:58:20.757+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-11-02T17:58:21.003+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/customer_churn_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/customer_churn_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/customer_churn.py", line 17, in glue_job_s3_redshift_transfer
    client.start_job_run(
  File "/home/ubuntu/customer_churn_venv/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/customer_churn_venv/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ConcurrentRunsExceededException: An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded for s3_upload_redshift_gluejob
[2023-11-02T17:58:21.008+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag, task_id=tsk_glue_job_trigger, execution_date=20231102T175739, start_date=20231102T175820, end_date=20231102T175821
[2023-11-02T17:58:21.020+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task tsk_glue_job_trigger (An error occurred (ConcurrentRunsExceededException) when calling the StartJobRun operation: Concurrent runs exceeded for s3_upload_redshift_gluejob; 1690)
[2023-11-02T17:58:21.038+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-02T17:58:21.055+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
